### ISSUE TITLE
Support other browsers

### ISSUE THREAD

**Issue by ergo** [FabricElements/skeleton-carousel#14]
Hello,

The carousel element works fine for me under chromium but is currently broken under Firefox 56.

Only some parts of UI render correctly.

**Comment by ergo** [comment]
Rendering issues are also visible on Internet Explorer 11 and latest MS Edge browser.

**Comment by ernysans** [comment]
@stivaliserna Please verify this and review if this a ES6 support issue. In that case make a ES5 build to see if everything runs fine.

**Comment by ernysans** [comment]
@ergo Thank you for reporting this issue. We just released a new version where this should be fixed.
