### ISSUE TITLE
Hybrid Element

### ISSUE THREAD

**Issue by JaySunSyn** [FabricElements/skeleton-carousel#17]
Hi Erny!
Thanks for this element!

I'd need it to be hybrid in order to use it in my apps.

I've created a hybrid version of it here: https://github.com/JaySunSyn/skeleton-carousel/tree/hybrid

May you:
- create a new branch e.g. `hybrid`

Then I can PR against it.

The only question would be which version to release... PolymerElements are using 2.x.x for hybrid elements. But you already released the Polymer 2 element with this scheme. Maybe `2.0.0h`or `3.0.0`?

Install `polymer install --variants` and run `polymer serve -o` to see that both versions are working.

**Comment by ernysans** [comment]
Hi Jalal, thank you for your work on this. You can now send the PR to `hybrid` so you can keep working on this, we can discuss the version name for it once this is ok.
Please make sure to run `npm run lint`, you have multiple errors there and your PR wont pass travis without it.

**Comment by ernysans** [comment]
@JaySunSyn  I just closed your PR. I'm updating the 2.x version the new mixins to keep it consistent.
We decided that we are going to use the 1.x.x for hybrid components.
Once I push the new updates I'll publish a new release.
Thank you for taking the time to work on this.

**Comment by ernysans** [comment]
@JaySunSyn I just released v2.0.4. I worked on a lot of issues and cleaned up the code even more.
Your hybrid version will continue to have some problems on mobile when you try to drag the images.
You can check out the new version where I was able to fix it.

**Comment by JaySunSyn** [comment]
Thanks for the release @ernysans! I'll look into the changes :)

**Comment by ernysans** [comment]
Hi @JaySunSyn. New updates on master. We are going to add keyboard navigation and updates on the documentation. I will recommend you to hold until the end of the week to work on the hybrid so you don't have to do that many changes.

**Comment by ernysans** [comment]
@JaySunSyn  We are almost done with the updates for the release. I'll notify you so you can update the hybrid component.

**Comment by ernysans** [comment]
@JaySunSyn I just published this week release for the 2.0 version. We perform a lot of changes and improvements. Let me know if you have the time to work on this.

Please change your bower.json version to `1.0.1`

**Comment by JaySunSyn** [comment]
Hi Erny! I think I'll copy skeleton-carousel.html and make it compatible for Polymer 1 rather than cherry pick your changes. (as there are a lot of changes).
Let me know when you think most changes are implemented for now..

**Comment by ernysans** [comment]
@JaySunSyn We are not going to touch this component for a while. We already implemented everything that we needed for now, including documentation and tests.

**Comment by ernysans** [comment]
@JaySunSyn Thank you for working on the hybrid version. I just released the new version `v.1.0.2`. 🎉
