### ISSUE TITLE
Feature Request: autoplay

### ISSUE THREAD

**Issue by andrewspy** [FabricElements/skeleton-carousel#23]
I would like to request an `autoplay` feature, where the carousel will autoplay after x seconds, which is also a common use case.

Thanks!

**Comment by ernysans** [comment]
Hi @andrewspy. Thank you, we are planing to implement it for our next release. We are working on adding keyboard controls right now. We can try to work on this too.

**Comment by ernysans** [comment]
@stivaliserna We can talk about this over the week.

**Comment by ernysans** [comment]
@andrewspy This feature is available in our latest release.
Run this first:
```bash
$ bower cache clean
````

**Comment by andrewspy** [comment]
I have tested it and and it's working as expected. Thanks!

Noticed a small typo on `durantion` in `README.md`.
