### ISSUE TITLE
Expose selected-item

### ISSUE THREAD

**Issue by JaySunSyn** [FabricElements/skeleton-carousel#27]
`selectedItem` should be the node where the class `selected` is added to.
e.g.: I currently need to check if iron-image has already loaded the image. Having selectedItem exposed, would make this much easier.

**Comment by ernysans** [comment]
@JaySunSyn thanks for the update. I'm trying to use iron-selector to clean it even more. I'll push the changes later today.

**Comment by JaySunSyn** [comment]
Thanks!
