### ISSUE TITLE
Add animationActive property

### ISSUE THREAD

**Issue by JaySunSyn** [FabricElements/skeleton-carousel#30]
I'd like to know when the animation
- to the next slide
- to the initial position of the current slide
has ended.

e.g. by setting an `animationActive` property. 

`swiping` => user actively swipes => shorter active than `animationActive` because carousel needs to slide back or to next slide.

**Comment by ernysans** [comment]
@JaySunSyn I'm not sure how to accomplish this

**Comment by JaySunSyn** [comment]
Sure, I've implemented an approach here https://github.com/FabricElements/skeleton-carousel/pull/32

Let me know if that's cool with you.

**Comment by ernysans** [comment]
@JaySunSyn -> New `animating` property and `animating-changed` event. I did a few modifications to make it work better. Thanks again.
