### ISSUE TITLE
Your component is featured in one of the Vaadin blog

### ISSUE THREAD

**Issue by binhbbbb** [FabricElements/skeleton-carousel#68]
Hi FabricElements team,

I wrote a blog [8 best Polymer carousel web components for your next web app](https://vaadin.com/blog/10-best), featuring skeleton-carousel. I tested it and think that it is a super cool component.

It will be extremely great to have some words from the original author under the comment section, and if possible, on this [tweet](https://twitter.com/binhbbbb/status/991599744215666688) also.

Cheers!

**Comment by ernysans** [comment]
@binhbbbb Thank you for including our component in your blog post and the vaadin directory
