### ISSUE TITLE
How can we use this carousel in Polymer 3 ?

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [FabricElements/skeleton-carousel#70]

**Comment by ernysans** [comment]
@AnkitMaheshwariIn There is not support in polymer 3 for Polymer 2 component at this moment so it's not possible for now.

**Comment by evancaldwell** [comment]
@ernysans you should be able to run the Polymer Modulizer on this and get it Polymer 3 compliant pretty easily. Then you would just publish it out on NPM. I'd love to use it as well.

**Comment by evancaldwell** [comment]
Sounds good. Thanks guys.

**Comment by AnkitMaheshwariIn** [comment]
@ernysans Thanks! Looking forward to see in 3.0-preview.

**Comment by ernysans** [comment]
Good news everyone. We have pushed a new branch so you can play around with `skeleton-carousel` 3.0. We are working on testing but the component is fully functional and has been updated the right way so you can go and test it now.

```shell
$ npm i FabricElements/skeleton-carousel#3.0-preview --save
```

@evancaldwell @AnkitMaheshwariIn

**Comment by AnkitMaheshwariIn** [comment]
@ernysans Thanks a lot! I'll try it very soon.

**Comment by stivaliserna** [comment]
Hey! All tests passed, make sure you run `polymer test --npm`. Like @evancaldwell said, the migration was pretty easy running Polymer Modulizer.
