### ISSUE TITLE
Duration of the carousel become chaotic after vertical and horizontal swipe on v2.0.6

### ISSUE THREAD

**Issue by andrewspy** [FabricElements/skeleton-carousel#82]
I have just tried out the newly release v2.0.6, and noticed that the duration of the carousel become chaotic after swiping both vertically and horizontally randomly. In my case, I have set the duration to be 7000ms, but after swiping vertically (on page) and horizontally (on carousel) randomly, the duration become chaotic (i.e. random duration, may be as short as 500ms - 1000ms)

**Comment by ernysans** [comment]
@stivaliserna Please let me know if this issue was solved so we can release a new version

**Comment by stivaliserna** [comment]
@ernysans Yup! fixed in #83

**Comment by andrewspy** [comment]
The problem seems to be resolved in v2.0.7, thanks for the quick response.

Closing the issue with thanks!
